### ISSUE TITLE
Prompt: SharpTabs has been uninstalled and cannot run.

### ISSUE THREAD

**Issue by Pluto1219** [samuelventura/SharpTerminal#2]
![image](https://user-images.githubusercontent.com/15402976/98101373-138bf380-1ecd-11eb-90ea-11f81ab43053.png)

**Comment by samuelventura** [comment]
SharpTabs is common to SharpTerminal and SharpMaster. It needs to be cloned in same directory as SharpTerminal. Eventually SharpTabs will be referenced from nuget but it is a source dep right now. You may want to clone v1.0.8 which is self contained instead.
